apiVersion: v1
kind: Service
metadata:
  name: server
  namespace: default
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: server
  type: ClusterIP